//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Opten.Core")]
[assembly: AssemblyDescription("Opten.Core")]
[assembly: AssemblyCompany("OPTEN AG")]
[assembly: AssemblyProduct("Opten.Core")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2019 OPTEN AG")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: ComVisible(false)]

[assembly: InternalsVisibleTo("Opten.Core.Test")]

