//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Opten.Core")]
[assembly: AssemblyDescription("Opten.Core")]
[assembly: AssemblyCompany("OPTEN AG")]
[assembly: AssemblyProduct("Opten.Core")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2019 OPTEN AG")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("9bdd55f1-4f66-448c-9df4-836c1093f83f")]

[assembly: InternalsVisibleTo("Opten.Core.Test")]

